# Generated by Django 2.0.3 on 2018-04-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('1', 'Горячее'), ('2', 'Супы'), ('3', 'Закуски'), ('4', 'Напитки')], max_length=1, verbose_name='Тип еды'),
        ),
    ]
