# Generated by Django 2.0.3 on 2018-04-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20180412_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.IntegerField(choices=[(1, 'Горячее'), (2, 'Супы'), (3, 'Закуски'), (4, 'Салаты'), (5, 'Выпечки'), (6, 'Напитки')], verbose_name='Тип еды'),
        ),
    ]
